name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  AZURE_CONTAINERAPPS_ENVIRONMENT: ${{ vars.AZURE_CONTAINERAPPS_ENVIRONMENT || 'my-env' }}
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP || 'my-resource-group' }}
  CONTAINERAPP_NAME: ${{ vars.CONTAINERAPP_NAME || 'node-express-app' }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME || 'node-express-devops-sample' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acr-name: ${{ vars.ACR_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          container-app-name: ${{ env.CONTAINERAPP_NAME }}
          image-to-deploy: ${{ vars.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
